### ISSUE TITLE
triggering the driverbuild 

### ISSUE THREAD

**Issue by jnunyez** [silicomDK/sts2-charts#3]
I saw that BuildConfig object  has no trigger or ImageStream and were deleted. These objects were present  in the BuildConfig here: https://github.com/silicomDK/sts2-charts/blob/a670cf44dd3f9b820d83935d61fcaf2a05831e61/charts/sts-silicom-0.0.1/templates/0000-state-driver-buildconfig.yaml

I was not able to properly reproduce the whole driver-build process without these trigger. Was there any reason to delete them?

**Comment by rmr-silicom** [comment]
I removed the ImageStream because as of now, it is not based on a git source which it can see? I mean trigger on changes. I don't see the reason for it if it is offline and the source is offered via http. But maybe i don't fully understand the ImageStream
